#
# Use nix-emacs-ci for travis CI
# URL: https://github.com/purcell/nix-emacs-ci
#

language: nix

os:
  - linux

env:
  - EMACS_CI=emacs-26-1
  - EMACS_CI=emacs-27-1
  - EMACS_CI=emacs-snapshot

install:
  # The default "emacs" executable on the $PATH will now be the version named by $EMACS_CI
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
  - nix-env -iA nixpkgs.cask
  # install deps for cask
  - export PATH=$HOME/.cask/bin:$PATH
  - travis_retry eval $"cask install ; sleep 10"

script:
  - export PATH=$HOME/.cask/bin:$PATH
  - emacs --version
  - cask exec ert-runner
